### ISSUE TITLE
Stupid question, but what is the use of this package?

### ISSUE THREAD

**Issue by philippejadin** [webstronauts/php-unpoly#1]
Hello,
I guess I can already say thank you because this package will probably help me for my use, but I'm not sure at this point :-)

I have a laravel app that uses unpoly a lot, and I need to return the correct response types (for example up-follow to a 404 page doesn't work since laravel will return json instead of html fragment).

Is it the purpose of this package? If so do I need to add the created unpoly middleware to all routes?

Thank you  (and sorry for the silly question :-) )

**Comment by robinvdvleuten** [comment]
The Unpoly library is originally build for Rails, where you can manage different output responses more easily. They also do not force to return everything as JSON when the client makes an XHR request. I guess that's because they have their UJS / SJR paradime (https://signalvnoise.com/posts/3697-server-generated-javascript-responses). 

The problem with Laravel and Unpoly is that - under the hood - a lot of things happen regarding handling XHR responses. They force everything to be returned by JSON in their error handler for example. 

So one thing that definitely helps you with integrating Unpoly is to implement the `convertValidationExceptionToResponse` method (https://github.com/webstronauts/php-unpoly#validation-errors). But if you want more control over other exception types, my suggestion would be to override the `render` method (https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Exceptions/Handler.php#L189) in a similar fashion.

The solely purpose of the library is to mimic Unpoly's functionality within the Ruby gem as middleware for a PHP framework based on Symfony. The one thing you definitely need to do is to add the Unpoly middleware to all of your `web` routes. I've added some more guidelines how to use it with Laravel, but these can be improved.  

Regarding the question about your 404 page. It feels weird to me that a route generated by your application can return a 404 in the first place. The only 404s I encounter in my apps are from a user typing in a different path in the browser, so the default - non Unpoly - 404 response can be used. Can you maybe explain your case a bit further so I can understand it better?

**Comment by philippejadin** [comment]
Thank you for the detailed reply.

So to sumarize, the package add the same helpers as the ruby gem as described here : https://www.rubydoc.info/github/unpoly/unpoly/master ?

For unpoly + laravel, it would be really cool to also have some documentation on how to overide the `render` method like you suggest. I have to say that I tried, but didn't manage to do it. Since this method is quite important, I don't dare to touch it without expert knowledge :-)

Here is what I have, that doesn't work properly and feels unclean : 
```

public function render($request, Throwable $exception)
    {
        if ($request->hasHeader('X-Up-Target')) {
            if (method_exists($exception, 'render') && $response = $exception->render($request)) {
                return Router::toResponse($request, $response)->header('Content-Type', 'text/html');
            } elseif ($exception instanceof Responsable) {
                return $exception->toResponse($request)->header('Content-Type', 'text/html');
            }

            $exception = $this->prepareException($exception);

            if ($exception instanceof HttpResponseException) {
                return $exception->getResponse();
            } elseif ($exception instanceof AuthenticationException) {
                return $this->unauthenticated($request, $exception);
            } elseif ($exception instanceof ValidationException) {
                return $this->convertValidationExceptionToResponse($exception, $request);
            }

            return $this->prepareResponse($request, $exception);
        }

        return parent::render($request, $exception);
    }
```

You are right with the 404, it was just an example. A more accurate one would be 500's that are silently not shown by unpoly, this is a major problem, since we are supposed to "fail loudly".

Sorry this discussion is starting more like a support request. If you prefer I ask somewhere else. But to be honest this is the only place where laravel + unpoly is even mentioned it seems.

**Comment by philippejadin** [comment]
I made my homework (I hope), this is the render method I now have in `app/Exceptions/Handler` :

```
public function render($request, Throwable $e)
    {
        if (method_exists($e, 'render') && $response = $e->render($request)) {
            return Router::toResponse($request, $response);
        } elseif ($e instanceof Responsable) {
            return $e->toResponse($request);
        }

        $e = $this->prepareException($e);

        if ($e instanceof HttpResponseException) {
            return $e->getResponse();
        } elseif ($e instanceof AuthenticationException) {
            return $this->unauthenticated($request, $e);
        } elseif ($e instanceof ValidationException) {
            return $this->convertValidationExceptionToResponse($e, $request);
        }

        if ($request->hasHeader('X-Up-Target')) {
            return $this->prepareResponse($request, $e);
        }

        return $request->expectsJson()
        ? $this->prepareJsonResponse($request, $e)
        : $this->prepareResponse($request, $e);
    }
```

**Comment by robinvdvleuten** [comment]
I guess I was the only one even trying to get Unpoly working within a non-Rails app, so it's nice to help someone with similar problems I had at the beginning :) 

It's quite easy actually to override the `render` method, just tweak the ternary operator at the last line;

```php
<?php

public function render($request, Exception $e)
{
    if (method_exists($e, 'render') && $response = $e->render($request)) {
        return Router::toResponse($request, $response);
    } elseif ($e instanceof Responsable) {
        return $e->toResponse($request);
    }

    $e = $this->prepareException($e);

    if ($e instanceof HttpResponseException) {
        return $e->getResponse();
    } elseif ($e instanceof AuthenticationException) {
        return $this->unauthenticated($request, $e);
    } elseif ($e instanceof ValidationException) {
        return $this->convertValidationExceptionToResponse($e, $request);
    }

    return $request->expectsJson() && ! $request->hasHeader('X-Up-Target')
        ? $this->prepareJsonResponse($request, $e)
        : $this->prepareResponse($request, $e);
}
```

Do note that you still have to check for Unpoly requests in both the `unauthenticated` and `convertValidationExceptionToResponse` though. As they return a response before the ternary operator is reached.
 
Another solution would be to create a custom `Request` instance as mentioned here (https://stackoverflow.com/questions/30155500/extend-request-class-in-laravel-5). Then you can override the `expectsJson` method with something like;

```
public function expectsJson()
{
    return parent::expectsJson() && ! $request->hasHeader('X-Up-Target');
}
```
