### ISSUE TITLE
Your experience integrating Unpoly?

### ISSUE THREAD

**Issue by stevebauman** [webstronauts/php-unpoly#2]
Hi @robinvdvleuten! Thanks for this excellent package!

This isn't an issue or bug (everything is working great!), but I wanted to ask how your experience has been integrating Unpoly in an app (whether it be a Laravel or Symfony app) and if you encountered any gotchas along the way?

I'm a lone dev, so I've shot myself in the foot using large front-end frameworks like Vue / React in the past building a SPA and having to build and write tests for frontend and backend.

I'm looking for something to enhance my server-rendered Laravel web apps. I've used Turbolinks in the past, but Unpoly looks like it has more features to make apps feel more SPA like.

I'd really value your opinion if you'd like to share it, thanks for your time!

**Comment by robinvdvleuten** [comment]
Thank you for these kind words @stevebauman, really appreciated!

I ran into some issues with Laravel and Unpoly at first. But when overcome, the UX is way better than when you integrate something like Turbolinks into Laravel and do all the form handling through custom Javascript. I've noted some of the global issues in here https://github.com/webstronauts/php-unpoly/issues/1#issuecomment-628446592.

You'll run into similar issues when you use Symfony, but they are easier to handle. That's because Symfony is less opinionated in how AJAX requests should be handled (especially validation issues).  

But I had never an issue with Unpoly itself, it is quite a stable framework and very well documented. 

Are there currently any issues you run into right now while integrating Unpoly with your backend app?

**Comment by stevebauman** [comment]
> the UX is way better than when you integrate something like Turbolinks into Laravel and do all the form handling through custom Javascript.

This is exactly what I was curious about -- this is great to know! I was doing all of this manually as well, but playing with Unpoly -- it works excellently.

> Are there currently any issues you run into right now while integrating Unpoly with your backend app?

So far I've been able to integrate mostly everything I need, such as:

- Flash notifications
- Form validation & AJAX submission
- Turbolinks navigation (using `up-follow` on links)
- Refresh dynamic data via polling ([here](https://github.com/unpoly/unpoly/issues/63#issuecomment-645093468))

The only thing remaining really is:

- Data tables (such as re-ordering columns + searching)
- Handling 500 server errors (Unpoly spits out Laravel's JSON exception on the entire page, replacing the whole `<body>` element)

 Have you dealt with these before?

**Comment by thewebartisan7** [comment]
I never work with unpoly, I found it today. I am using Laravel as well and I would like to know if you have fixed last mention issue with error exception? Did you add add exception handler as explained here https://github.com/webstronauts/php-unpoly#validation-errors ? Seem like a solution for fix your issue.

@robinvdvleuten there is another way for avoid to change public/index.php ?

**Comment by stevebauman** [comment]
Hi @thewebartisan7 -- I actually wrote the PR that included that documentation 👍 

https://github.com/webstronauts/php-unpoly/commit/5063951f4a48ff367b9e63866f8fee029d9e7ea1

This is a stale issue, as I've already resolved it using the above mentioned PR. I have not found another way of handling other HTTP errors unfortunately. This appears to be the only way (that I know of).

**Comment by triskweline** [comment]
I don't know if this helps, but the upcoming Unpoly version will no longer replace the whole page when a JSON response is received. Instead it will emit an `up:fragment:unusable` event which you may handle on the client side, e.g. to display an error message or redirect to a login screen.

**Comment by stevebauman** [comment]
That's great @triskweline! Thanks for the update 👍
